#!/bin/python3

import sys


n = int(input().strip())
s = (input().strip())
c=0
for i in range(0,len(s)):
    #print(s[i:i+3],"fdefheuh")    
    if s[i:i+3]=="010":
        #print(s[i:i+3])
        c+=1
        s=list(s)
        s[i+2]='1'
        s=''.join(s)
        #print(s)
    if i+3==len(s):
        break
print(c)
        

