#!/bin/python3

import sys


n,k = input().strip().split(' ')
n,k = [int(n),int(k)]
a = [int(a_temp) for a_temp in input().strip().split(' ')]
l,c=len(a),0
for i in range(l):
    for j in range(i+1,l):
        if (a[i]+a[j])%k==0:
            #print(a[i],a[j])
            c=c+1
print(c)
